import pandas as pd
import pathlib
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np  # Used for the simple mean calculation

# --- Path Configuration ---
THIS_DIR: pathlib.Path = pathlib.Path(__file__).resolve().parent
PROJECT_ROOT_DIR: pathlib.Path = THIS_DIR.parent.parent.parent
DATA_DIR: pathlib.Path = PROJECT_ROOT_DIR / "data"
OLAP_OUTPUT_DIR: pathlib.Path = DATA_DIR / "olap_cubing_outputs"

# IMPORTANT: Use the file name generated by the cubing script
CUBE_FILENAME = "multidimensional_olap_cube.csv"
CUBE_PATH: pathlib.Path = OLAP_OUTPUT_DIR / CUBE_FILENAME
# --- End Configuration ---


def load_cube_data() -> pd.DataFrame:
    """Loads the pre-calculated OLAP cube."""
    if not CUBE_PATH.exists():
        print(f"Error: Cube file not found at {CUBE_PATH}. Please run cubing.py first.")
        return pd.DataFrame()

    cube_df = pd.read_csv(CUBE_PATH)
    print(f"Cube loaded successfully. {len(cube_df)} combinations found.")
    return cube_df


def perform_olap_analysis(df: pd.DataFrame):
    """Executes Slicing, Dicing, and prepares data for Drilldown and Visualization."""

    # Ensure correct column name is used based on cubing.py output
    REVENUE_COL = 'sale_amount_sum'

    print("\n--- OLAP Analysis Execution ---")

    # 1. SLICING (Filtering by a single dimension value)
    # Goal: Extract the profitability slice for a specific region (e.g., 'EAST').
    target_region = 'EAST'
    slice_view = df[df['region'] == target_region].sort_values(by=REVENUE_COL, ascending=False)

    print(f"\n1. SLICING: Top 3 Categories in the {target_region} Region:")
    print(slice_view[['category', REVENUE_COL]].head(3).to_markdown(index=False))

    # 2. DICING (Filtering by multiple criteria to define a sub-cube)
    # Goal: Identify categories with below-average profitability across all regions.
    mean_revenue_per_combo = df[REVENUE_COL].mean()
    dice_view = df[
        (df['region'] != target_region)  # Focus on regions OTHER than EAST
        & (df[REVENUE_COL] < mean_revenue_per_combo)
    ].sort_values(by=REVENUE_COL)

    print("\n2. DICING: Below-Average Revenue Combinations (Excluding EAST):")
    print(f" (Mean Revenue Threshold: {mean_revenue_per_combo:,.2f} USD)")
    print(dice_view[['region', 'category', REVENUE_COL]].to_markdown(index=False))

    # Prepare Pivot Table for Visualization
    pivot_table = df.pivot_table(
        index='category', columns='region', values=REVENUE_COL, fill_value=0
    )

    return pivot_table, dice_view


def visualize_results(pivot_table: pd.DataFrame):
    """Creates the main visualization (Heatmap) for the report and saves it."""

    plt.figure(figsize=(12, 8))
    # Generate the Heatmap
    sns.heatmap(
        pivot_table,
        annot=True,
        fmt=",.0f",  # Format numbers with commas
        cmap="YlGnBu",
        linewidths=0.5,
        cbar_kws={'label': 'Total Revenue (USD)'},
    )
    plt.title('Category Profitability by Region (Total Revenue)', fontsize=16)
    plt.ylabel('Product Category')
    plt.xlabel('Customer Region')
    plt.tight_layout()

    viz_path = OLAP_OUTPUT_DIR / "category_region_heatmap.png"
    plt.savefig(viz_path)
    print(f"\n3. VISUALIZATION: Heatmap saved to {viz_path}")
    # The image is saved to the file system.


def main_analysis():
    """Main function to run the analysis and visualization."""
    cube_df = load_cube_data()
    if cube_df.empty:
        return

    # Perform Analysis and get Pivot Table
    pivot_table_result, dice_view = perform_olap_analysis(cube_df)

    # 3. DRILLDOWN (Exploration) - DOCUMENTATION ONLY
    worst_combination = dice_view.iloc[0] if not dice_view.empty else None

    print("\n3. DRILLDOWN (Documentation of intent):")
    if worst_combination is not None:
        # Note: Actual Drilldown requires the raw joined data (final_df), not the cube.
        print(
            f"   - Intent: Drill down into the lowest performing combination: {worst_combination['category']} in {worst_combination['region']}."
        )
        print(
            "   - Action: Query the raw data to check performance at the 'product_name' level for this specific category/region."
        )
        print(
            "   - Goal: Determine if one or two underperforming products are driving the low category revenue."
        )

    # Visualization
    visualize_results(pivot_table_result)


if __name__ == "__main__":
    main_analysis()
